######################################################################
# Automatically generated by qmake (2.01a) Mon Feb 13 16:09:43 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += clihw.cpp guihw.cpp \
    window.cpp

HEADERS += \
    window.h
