first:
	g++ first.cpp -std=c++11 -o /tmp/first.out && /tmp//first.out

links:
	g++ links.cpp -std=c++11 -o /tmp/$@.out && /tmp/$@.out

startLearnTasks:
	g++ startLearnTasks.cpp -std=c++11 -o /tmp/a.out && /tmp/a.out

