######################################################################
# Automatically generated by qmake (3.0) Thu Feb 16 13:17:15 2017
######################################################################

TEMPLATE = app
TARGET = qt
INCLUDEPATH += .
QT += network widgets
QMAKE_CXXFLAGS += -std=c++11
CONFIG += c++11

# Input
HEADERS += ser.h cli.h client.h
SOURCES += main.cpp client.cpp ser.cpp cli.cpp
