######################################################################
# Automatically generated by qmake (3.0) Thu Feb 16 13:17:15 2017
######################################################################

TEMPLATE = app
TARGET = qt
INCLUDEPATH += .
QT += network widgets

# Input
HEADERS += ser.h cli.h
SOURCES += main.cpp ser.cpp cli.cpp
